### ISSUE TITLE
SVG classes are blocked by AdGuard

### ISSUE THREAD

**Issue by pixelstrolch** [FlorianBrinkmann/svg-social-menu#2]
My Ad blocker [AdGuard](https://adguard.com) loads a CSS rule which blocks the classes `.icon-twitter` or `.icon-pinterest`. Could you prefix those CSS classes to avoid this?

Here the whole CSS rule from AdGuard:
```css
.cross_socia, .csbwfs-social-widget, .dcssb-float, .essb_links, .essb_share, .et_social_facebook, .et_social_icons_container, .et_social_networks, .et_social_pinterest, .et_social_sidebar_networks, .et_social_twitter, .etsy-pin-it, .etsy-tweet, .fa-facebook-square, .fa-google-plus-square, .fa-linkedin-square, .fa-pinterest-square, .fa-reddit-square, .fa-tumblr-square, .fa-twitter-square, .fa-youtube-square, .facebook-like, .facebook-share, .facebook-small, .facebook_like_box, .facebook_share_size_Small, .facebooklike, .fb-button, .fb-like-box, .fb-like-button, .fb-page, .fb-share, .fb-share-button, .fb-share-container, .fb_like_contain, .fb_share, .fb_widget, .fblike, .fbx-social, .field-name-horizontal-social-widgets, .floatee-social-tail, .followFacebook, .followTwitter, .followYoutube, .g1-sharebar, .g_plus, .gig-share-bar-container, .goodshare, .google-plus-follow, .google-plus1, .google-share, .google_plus1_badge, .googleplus-one, .gplus-like-button, .gs-share, .hdsocial2, .header-social, .heart-button, .heart-it-button, .help-social-buttons, .i_v_fb_like, .icon-digg, .icon-pinterest, .icon-pinterest-share, .icon-reddit, .icon-stumbleupon, .img__sharer, .inline_socials, .j_social_share, .js-shares, .js-socialise, .js-socialise-wrapper, .jssocials-shares, .large_share_holder, .lazysocialbuttons, .like_buttons, .like_fb_like_action, .likely, .likes-bar, .likes_block, .lj-like, .lj-like-item, .mashsb-container, .mashsb-main, .mc-share-cnt, .mod-follow, .mod-stay-connected, .mom-social-share, .mvp_facebook_widget, .news_social_button, .p-button-social, .page-share, .page-share-button, .pin-it-button, .pinit-btn, .pinterest-share, .pinterest-share-button, .pinterest-sharetool, .pinterest-small, .pluso, .pocket-btn, .popup-social, .post-item__social, .post-share, .post-share-box, .post-share-buttons, .post-share-links, .post-share-widget, .post-social-facebook, .post-social-gplus, .post-social-tweet, .post-social-vk, .post_likes, .pp_socialButton, .really_simple_share, .recommend_fb_like_action, .rt_share, .s-sharelist, .serp-adv__banner, .share-article, .share-article-social, .share-article-tools, .share-article-vertical, .share-bar-desktop, .share-block, .share-bottom, .share-btn, .share-btns, .share-button, .share-buttons-multi, .share-cont, .share-counter, .share-facebook, .share-general, .share-gplus, .share-help, .share-icons-box, .share-icons-sticky-box, .share-icons-wrap, .share-link, .share-pictures-overlay, .share-proposal, .share-regular, .share-sm-icons, .share-tools, .share-wrap, .share3, .share42init, .shareBar, .shareButtons, .shareComment, .shareLinks, .shareSocialArticle, .shareThis, .shareThis__cue, .shareThis__wrapper, .shareWrapper, .share__button, .share__buttons, .share_absolute, .share_bar, .share_block, .share_btns, .share_buttons, .share_click, .share_count, .share_links, .share_menu, .share_panel, .share_tools, .shareaholic-canvas, .sharebar, .shared-item-icon, .sharedaddy, .sharedefault, .shareholder, .shareit, .sharelinks, .sharelist, .sharelist_vertical, .sharepost, .sharethis, .sharethis-container, .sharethisawrp, .sharetools, .sharing-item, .sharing-popup-social, .sharing-tools, .sharing_controls, .sharrre, .sharrre-container, .sharrre_widget, .side-social-links, .sideBarShare, .sideSocial, .sidebar-share, .single-post-sharing-button, .soc-button, .soc-likes, .soc-links, .soc24, .socBmFb, .socBmTw, .socFbShare, .socLinks, .socRight, .soc_button_sw, .soc_buttons, .soc_like, .soc_share, .soc_tabs, .socbclass, .socbuttons, .sociable, .social-bar, .social-block, .social-block-div, .social-block-links, .social-block-share, .social-button, .social-button-small, .social-button_holder, .social-fb-alt2, .social-fp-widget, .social-horizontal, .social-likes, .social-likes_single-w, .social-line, .social-links-tooltip, .social-love, .social-media-box, .social-media-iframe, .social-menu, .social-networks, .social-profiles-widget, .social-roll, .social-row, .social-service, .social-share, .social-share-bar, .social-share-buttons, .social-share-buttons-block, .social-share-facebook, .social-share-google, .social-share-ic, .social-share-links, .social-share-twitter, .social-share-widget, .social-shares, .social-sharing, .social-sidebar-wrap, .social-sitewide, .social-sticky, .social-tab, .social-tab-large {
    display: none!important;
}
```
